[package]
name = "web_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
tgl_rando_core = { path = "../tgl_rando_core" }
dioxus = { version = "=0.5.6", features = ['web'] }
dioxus-web = "=0.5.6"
hex = "0.4.3"
