[package]
name = "tgl_rando_core"
version = "0.1.0"
edition = "2021"

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
rand = { version = "0.8.5", features = ["std"] }
rand_chacha = "0.3.1"
rand_seeder = "0.3.0"
ndarray = "0.16.1"
hex = "0.4.3"

